### PR TITLE
add notebook to compute depth

### PR DESCRIPTION
**Pull request by dienhoa**
You find in this PR the notebook to create depth image sky masking. It is intended to use to avoid creating synthetic smoke in the sky

### CODE REVIEW

**Comment by MateoLostanlen** [comment]
Hi @dienhoa, Thanks for your PR. Can you add a python module instead ? It will be easier to integrate it into the dataset generation script

**Comment by dienhoa** [comment]
Sure, I will take a look at it maybe tomorrow

**Comment by dienhoa** [comment]
Updated with depth_estimation.py that can be import for further uses

**Review by jpennors — COMMENTED** [review]
@dienhoa I tried to refactor the depth estimation here : https://github.com/pyronear/synthetic-dataset/pull/9

**Comment by MateoLostanlen** [comment]
Thanks to both of you, I'm closing this beaucause everything it in #9 :)

**Pull request closed without merging**
